# Generated by Django 3.0.3 on 2020-03-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Costs', '0002_cost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='money',
            field=models.IntegerField(verbose_name='money'),
        ),
    ]
