# Generated by Django 3.0.4 on 2020-03-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('category', models.CharField(choices=[(1, 'Разное'), (2, 'Продукты'), (3, 'Транспорт'), (4, 'Развлечения')], default=1, max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
