# Generated by Django 3.0.4 on 2020-03-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='icon',
            field=models.CharField(choices=[(1, 'fas fa-puzzle-piece'), (2, 'fas fa-utensils'), (3, 'fas fa-bus'), (4, 'fas fa-gamepad')], default=1, max_length=50),
        ),
    ]
