# Generated by Django 3.0.4 on 2020-03-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_auto_20200319_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.IntegerField(choices=[('D', 'Разное'), ('F', 'Продукты'), ('C', 'Транспорт'), ('F', 'Развлечения')], default='D'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='icon',
            field=models.IntegerField(choices=[('D', 'fas fa-puzzle-piece'), ('F', 'fas fa-utensils'), ('C', 'fas fa-bus'), ('F', 'fas fa-gamepad')], default='D'),
        ),
    ]
