# Generated by Django 3.0.4 on 2020-03-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0007_auto_20200319_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.IntegerField(choices=[('Different', 'Разное'), ('Food', 'Продукты'), ('Cars', 'Транспорт'), ('Fun', 'Развлечения')], default='Different'),
        ),
    ]
