# Generated by Django 3.0.4 on 2020-03-19 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0009_auto_20200319_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Different', 'Разное'), ('Food', 'Продукты'), ('Cars', 'Транспорт'), ('Fun', 'Развлечения')], default='Different', max_length=30)),
                ('icon', models.CharField(choices=[('Different', 'fas fa-puzzle-piece'), ('Food', 'fas fa-utensils'), ('Cars', 'fas fa-bus'), ('Fun', 'fas fa-gamepad')], default='Different', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='cost',
            name='icon',
        ),
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costs.Category'),
        ),
    ]
