# Generated by Django 3.0.4 on 2020-03-31 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costs', '0012_auto_20200319_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costs', to=settings.AUTH_USER_MODEL),
        ),
    ]
