const FETCH_COSTS_SUCCESS = 'FETCH_COSTS_SUCCESS'
const FETCH_COSTS_REQUEST = 'FETCH_COSTS_REQUEST'
const FETCH_COSTS_FAILURE = 'FETCH_COSTS_FAILURE'

const COST_ADDED_TO_LIST = 'COST_ADDED_TO_LIST'
const COST_REMOVED_FROM_LIST = 'COST_REMOVED_FROM_LIST'

const FETCH_BALANCE_SUCCESS = 'FETCH_BALANCE_SUCCESS'
const FETCH_BALANCE_REQUEST = 'FETCH_BALANCE_REQUEST'
const FETCH_BALANCE_FAILURE = 'FETCH_BALANCE_FAILURE'

const FETCH_COST_SUM_SUCCESS = 'FETCH_COST_SUM_SUCCESS'
const FETCH_COST_SUM_REQUEST = 'FETCH_COST_SUM_REQUEST'
const FETCH_COST_SUM_FAILURE = 'FETCH_COST_SUM_FAILURE'

const FETCH_REPORT_SUCCESS = 'FETCH_REPORT_SUCCESS'
const FETCH_REPORT_REQUEST = 'FETCH_REPORT_REQUEST'
const FETCH_REPORT_FAILURE = 'FETCH_REPORT_FAILURE'

const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'
const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST'
const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE'

export {
    FETCH_COSTS_SUCCESS,
    FETCH_COSTS_REQUEST,
    FETCH_COSTS_FAILURE,
    COST_ADDED_TO_LIST,
    COST_REMOVED_FROM_LIST,
    FETCH_BALANCE_SUCCESS,
    FETCH_BALANCE_REQUEST,
    FETCH_BALANCE_FAILURE,
    FETCH_COST_SUM_SUCCESS,
    FETCH_COST_SUM_REQUEST,
    FETCH_COST_SUM_FAILURE,
    FETCH_REPORT_SUCCESS,
    FETCH_REPORT_REQUEST,
    FETCH_REPORT_FAILURE,
    FETCH_LOGIN_SUCCESS,
FETCH_LOGIN_REQUEST,
FETCH_LOGIN_FAILURE,
}